#!/usr/bin/env bash
# shellcheck disable=SC2016,SC2068


# = A list of common directories exempt from classification under installed
# directories
#
# For use with `collect_dirs()`
common_dirs=(
    etc
    run
    srv
    usr
    usr/bin
    usr/include
    usr/lib
    usr/lib/firmware
    usr/lib/pkgconfig
    usr/libexec
    usr/sbin
    usr/share
    usr/share/aclocal
    usr/share/doc
    usr/share/info
    usr/share/man
    usr/share/man/man1
    usr/share/man/man2
    usr/share/man/man3
    usr/share/man/man4
    usr/share/man/man5
    usr/share/man/man6
    usr/share/man/man7
    usr/share/man/man8
    var
    var/cache
)


# = Determine whether a given file is a library
#
# A library is defined as a (non-symlink) file ending in one of the library
# extensions:
# - a
# - dll
# - jar
# - so*
#
# This function uses a regex to check file extensions. It does not read magic
# bytes.
#
# == Returns
# 0 => file is a library
# 1 => file is not a library
is_lib() {
    [[ $1 =~ \.(a$|dll$|jar$|so) ]] &&
        [ ! -L "$1" ]
}


# = Determine whether a given file is a program
#
# A program is defined as an executable file directly under a directory
# '/bin/' or '/sbin/'.
#
# Note this function does not check whether a directory or file is passed. A
# file should be passed.
#
# == Returns
# 0 => file is a program
# 1 => file is not a program
is_prog() {
    [[ $1 =~ /s?bin/[^\/]+$ ]] &&
        [ -x "$1" ]
}


# = Determine whether a given file is firmware
#
# This function uses a regex to check file extensions. It does not read magic
# bytes.
#
# == Returns
# 0 => file is firmware
# 1 => file is not firmware
is_firm() {
    [[ $1 =~ \.(bin|bseq|ucode)$ ]]
}


# = Print usage to stderr and exit with code 2
usage() {
    cat >&2 << EOF
Usage: $0 <PACKAGE_NAME> <DESTDIR>

Reference docstubgen(1) for detailed documentation
EOF
    exit 2
}


# = Print version to stderr and exit with code 0
version() {
    cat << EOF
docstubgen-ng 0.0.0-dev
EOF
    exit 0
}


# = Helper function for debugging
#
# Prints $1 to stderr, prefixed by 'DEBUG:'
dbg() {
    if [ -n "${DOCSTUBGEN_DEBUG-}" ]; then
        echo "DEBUG: $1" >&2
    fi
}


# = Collects subdirectories into an array
#
# This function collects all leaf directories under $1 which are not in
# $common_dirs, with a maximum recursion depth defined by
# $DOCSTUBGEN_RECURSION_DEPTH, defaulting to 64.
#
# == Returns
# A sorted array of directories
collect_dirs() {
    local destdir="${1:?}"
    local dirlist
    local IFS=$'\n'

    # Find leaf directories (unix filesystems only)
    # https://stackoverflow.com/questions/4269798/use-gnu-find-to-show-only-the-leaf-directories
    #
    # NOTE: This does not find symlinks, and doing so is pretty complex, so
    # `collect_dirs()` does not discover symlinks
    readarray -t dirlist < <(
        find "$destdir" -mindepth 1 -maxdepth "${DOCSTUBGEN_RECURSION_DEPTH:-64}" -type d -links 2
    )

    # This ugly mess iterates over dirlist, and over common_dirs to determine
    # whether a directory should be retained. A directory should be retained if
    # not an element of $common_dirs.
    local trimmed_dirlist=()
    for dir in "${dirlist[@]}"; do
        # Trim out destdir prefix and leading /
        dir="${dir#*"${destdir}"}"
        dir="${dir#/}"

        # Match against common dirs to determine retention
        local retain=true
        for cdir in "${common_dirs[@]}"; do
            dbg "\$cdir = $cdir"
            dbg "\$dir  = $dir"
            if [[ $dir == $cdir ]]; then
                dbg "matched $dir against common dir $cdir"
                retain=false
                break
            fi
        done

        dbg "\$retain is set to $retain"
        if $retain; then
            trimmed_dirlist+=("$dir")
        fi
    done

    if [ "${#trimmed_dirlist[@]}" -gt 0 ]; then
        printf "/%s\n" "${trimmed_dirlist[@]}" | sort
    fi
}


# = Collects files into an array
#
# This function collects all files under $1, with a maximum recursion depth
# defined by $DOCSTUBGEN_RECURSION_DEPTH, defaulting to 64.
#
# == Returns
# filelist  : array (sorted)
collect_files() {
    local destdir="${1:?}"
    local filelist
    local IFS=$'\n'

    # Collect files and symlinks to files
    readarray -t filelist < <(
        find "$destdir" -mindepth 1 -maxdepth "${DOCSTUBGEN_RECURSION_DEPTH:-64}" -type f -o -type l -xtype f
    )

    printf "%s\n" "${filelist[@]}" | sort
}


# = Collects libraries into an array
#
# This function collects all libraries (as defined in `is_lib()`) under $1, with
# a maximum recursion depth defined by $DOCSTUBGEN_RECURSION_DEPTH, defaulting
# to 64.
#
# == Returns
# liblist   : array (sorted)
collect_libs() {
    local destdir="${1:?}"
    local contents=("$@")
    local liblist
    local IFS=$'\n'

    liblist=()
    for f in "${contents[@]}"; do
        if is_lib "$f"; then
            liblist+=("${f#*"${destdir}"}")
        fi
    done

    if [ "${#liblist[@]}" -gt 0 ]; then
        printf "%s\n" "${liblist[@]}" | sort
    fi
}


# = Collects programs into an array
#
# This function collects all programs (as defined in `is_prog()`) under $1, with
# a maximum recursion depth defined by $DOCSTUBGEN_RECURSION_DEPTH, defaulting
# to 64.
#
# == Returns
# proglist  : array (sorted)
collect_progs() {
    local destdir="${1:?}"
    local contents=("$@")
    local proglist
    local IFS=$'\n'

    proglist=()
    for f in "${contents[@]}"; do
        if is_prog "$f"; then
            proglist+=("${f#*"${destdir}"}")
        fi
    done

    if [ "${#proglist[@]}" -gt 0 ]; then
        printf "%s\n" "${proglist[@]}" | sort
    fi
}


# = Collects firmware into an array
#
# This function collects all firmware (as defined in `is_firm()`) under $1, with
# a maximum recursion depth defined by $DOCSTUBGEN_RECURSION_DEPTH, defaulting
# to 64.
#
# == Returns
# A sorted array of unformatted firmware files
collect_firm() {
    local destdir="${1:?}"
    local contents=("$@")
    local firmlist
    local IFS=$'\n'

    firmlist=()
    for f in "${contents[@]}"; do
        if is_firm "$f"; then
            firmlist+=("${f#*"${destdir}"}")
        fi
    done

    if [ "${#firmlist[@]}" -gt 0 ]; then
        printf "%s\n" "${firmlist[@]}" | sort
    fi
}


# = Format generically for display in the docstub
#
# This function takes a file as input and formats it. A formatted file is its
# basename. Links are mentioned in parentheses.
format_generic() {
    local original
    original="$(readlink "$1")"
    local file="${1##*/}"

    original="${original##*/}"
    printf "%s" "$file"
    [ -n "$original" ] && printf " (link to %s)" "$original"
}


# = Format a library for display in the docstub
#
# This function takes a library as input and formats it according to its type. A
# formatted library is the basename of a library, without its extension, with
# its type in parentheses if not a shared library.
format_library() {
    local lib="${1##*/}"
    case "$lib" in
        *.a)   printf "%s (static)"       "${lib%.a}"   ;;
        *.so*) printf "%s"                "${lib%.so*}" ;;
        *.jar) printf "%s (Java library)" "${lib%.jar}" ;;
        *.dll) printf "%s (DLL)"          "${lib%.dll}" ;;
        *)     printf "%s"                "$lib"        ;;
    esac
}


# = Format a library for display in the short descriptions section
#
# This effectively just prints the library without its extension
format_library_simple() {
    local lib="${1##*/}"
    case "$lib" in
        *.a)   printf "%s" "${lib%.a}"   ;;
        *.so*) printf "%s" "${lib%.so*}" ;;
        *.jar) printf "%s" "${lib%.jar}" ;;
        *.dll) printf "%s" "${lib%.dll}" ;;
        *)     printf "%s" "$lib"        ;;
    esac
}


# = Format the end of a new-line delimited list with commas and an 'and'
#
# Replaces ',' with ', and' on the second to last line. Removes ',' on the final
# line.
format_list_end() {
    sed -e 'x; ${s/,/, and/;p;x}; 1d' -e '$s/,//'
}


# = Formats all libraries
#
# This function takes an array, formats each individual library, prints it on
# its own line, intersperses commas, and adds an "and"
format_all_libraries() {
    case "$#" in
        0 ) printf "          None\n" ;;
        1 ) printf "          %s\n" "$(format_library "$1")" ;;
        2 )
            printf "          %s and\n" "$(format_library "$1")"
            printf "          %s\n" "$(format_library "$2")"
        ;;
        * )
            for name in "$@"; do
                printf "          %s,\n" "$(format_library "$name")"
            done | format_list_end
        ;;
    esac
}


# = Format a program for display in the docstub
#
# This function takes a program as input and formats it. A formatted program is
# its basename. Links are mentioned in parentheses.
format_program() {
    format_generic "$1"
}


# = Formats all programs
#
# This function takes an array, formats each individual program, prints it on
# its own line, intersperses commas, and adds an "and"
format_all_programs() {
    case "$#" in
        0 ) printf "          None\n" ;;
        1 ) printf "          %s\n" "$(format_program "$1")" ;;
        2 )
            printf "          %s and\n" "$(format_program "$1")"
            printf "          %s\n" "$(format_program "$2")"
        ;;
        * )
            for name in "$@"; do
                printf "          %s,\n" "$(format_program "$name")"
            done | format_list_end
        ;;
    esac
}


# = Format firmware for display in the docstub
#
# This function takes firmware as input and formats it. A formatted firmware
# file is its basename. Links are mentioned in parentheses.
format_firmware() {
    format_generic "$1"
}


# = Formats all firmware
#
# This function takes an array, formats each individual firmware, prints it on
# its own line, intersperses commas, and adds an "and"
format_all_firmware() {
    case "$#" in
        0 ) printf "          None\n" ;;
        1 ) printf "          %s\n" "$(format_firmware "$1")" ;;
        2 )
            printf "          %s and\n" "$(format_firmware "$1")"
            printf "          %s\n" "$(format_firmware "$2")"
        ;;
        * )
            for name in "$@"; do
                printf "          %s,\n" "$(format_firmware "$name")"
            done | format_list_end
        ;;
    esac
}


# = Format a directory for display in the docstub
#
# This function does not account for links as they aren't detected by
# `collect_dirs()` anyway.
format_directory() {
    printf "%s" "$1"
}


# = Formats all directories
#
# This function takes an array, formats each individual directory, prints it on
# its own line, intersperses commas, and adds an "and"
format_all_directories() {
    case "$#" in
        0 ) printf "          None\n" ;;
        1 ) printf "          %s\n" "$(format_directory "$1")" ;;
        2 )
            printf "          %s and\n" "$(format_directory "$1")"
            printf "          %s\n" "$(format_directory "$2")"
        ;;
        * )
            for name in "$@"; do
                printf "          %s,\n" "$(format_directory "$name")"
            done | format_list_end
        ;;
    esac
}

# = End and begin a <seg> tag in XML
segseg() {
cat << EOF
        </seg>
        <seg>
EOF
}


print_contents_header() {
cat << EOF
  <sect2 role="content">
    <title>Contents</title>

    <segmentedlist>
      <segtitle>Installed Programs</segtitle>
EOF
if [ ${#firmlist[@]} -gt 0 ]; then
    dbg "Firmlist has ${#firmlist[@]} entries"
cat << EOF
      <segtitle>Installed Firmware</segtitle>
EOF
fi
cat << EOF
      <segtitle>Installed Libraries</segtitle>
      <segtitle>Installed Directories</segtitle>

      <seglistitem>
        <seg>
EOF
}


# = Print the footer for the contents section
print_contents_footer() {
cat << EOF
        </seg>
      </seglistitem>
    </segmentedlist>

EOF
}


# = Print the header for the short descriptions section
print_shortdesc_header() {
cat << EOF
    <variablelist>
      <bridgehead renderas="sect3">Short Descriptions</bridgehead>
      <?dbfo list-presentation="list"?>
      <?dbhtml list-presentation="table"?>

EOF
}


# = Print the footer for the short descriptions section
print_shortdesc_footer() {
cat << EOF
    </variablelist>

EOF
}


# = Print the footer that ends the docstub
print_docstub_footer() {
cat << EOF
  </sect2>

</sect1>
EOF
}


# = Print the templates for the descriptions of all programs
describe_programs() {
for prog in "${proglist[@]}"; do
prog="${prog##*/}"
cat << EOF
      <varlistentry id="$prog">
        <term><command>$prog</command></term>
        <listitem>
          <para>
            <!-- TODO:  --> Description for $prog
          </para>
          <indexterm zone="$package $prog">
            <primary sortas="b-$prog">$prog</primary>
          </indexterm>
        </listitem>
      </varlistentry>

EOF
done
}


# = Print the templates for the descriptions of all libraries
describe_libraries() {
for lib in "${liblist[@]}"; do
lib="$(format_library_simple "${lib##*/}")"
cat << EOF
      <varlistentry id="$lib">
        <term><filename class="libraryfile">$lib</filename></term>
        <listitem>
          <para>
            <!-- TODO:  --> Description for $lib
          </para>
          <indexterm zone="$package $lib">
            <primary sortas="c-$lib">$lib</primary>
          </indexterm>
        </listitem>
      </varlistentry>

EOF
done
}


# = Main

[ -n "${DOCSTUBGEN_DEBUG-}" ] && : # set -x

for arg in "$@"; do
    case "$arg" in
        -h | --help ) usage ;;
        -V | --version ) version ;;
    esac
done

[ "$#" -lt 2 ] && usage

package="$1"
destdir="$2"

readarray -t contents < <(collect_files "$destdir")

if [ -n "$DOCSTUBGEN_DEBUG" ]; then
    dbg "Found contents: "
    printf "%s\n" ${contents[@]} >&2
fi

readarray -t dirlist < <(collect_dirs "$destdir")
readarray -t proglist < <(collect_progs "$destdir" "${contents[@]}")
readarray -t firmlist < <(collect_firm "$destdir" "${contents[@]}")
readarray -t liblist < <(collect_libs "$destdir" "${contents[@]}")
unset contents

print_contents_header

format_all_programs ${proglist[@]} && segseg
[ ${#firmlist[@]} -gt 0 ] && format_all_firmware ${firmlist[@]} && segseg
format_all_libraries ${liblist[@]} && segseg
format_all_directories ${dirlist[@]}

print_contents_footer

if [ "${#proglist[@]}" -eq 0 ] &&
   [ "${#liblist[@]}"  -eq 0 ] &&
   [ "${#firmlist[@]}" -eq 0 ]; then
    print_docstub_footer
    exit 0
fi

print_shortdesc_header

describe_programs
describe_libraries

print_shortdesc_footer
print_docstub_footer
