#!/bin/bash

# Helper script for checking files in docstubgen.
# (C) Seal Sealy 2025

# JARs are actually internally ZIP archives... sigh

if [ "${1##*.}" = "jar" ]; then
    file "$1" | grep "Zip" &> /dev/null && exit 0
fi

# ELF is binaries and shared libraries
# scripts is all kinds of misc .sh stuff and more
# ar archive is for static libs
# DLL is Windows DLLs
# JAR is some more obscure JAR files (there's one in the JDK that doesn't
# identify as a ZIP and instead identifies as a "Java archive data (JAR)")

file "$1" | grep -E "ELF|script|ar archive|DLL|JAR" &> /dev/null || exit 1
